---
version: "2.1"
services:
  golinks:
    image: nicholaswilde/golinks:latest
    container_name: golinks-default
    ports:
      - 8000:8000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - SUGGEST=https://suggestqueries.google.com/complete/search?client=firefox&q=%s
      - TITLE=Search
      - URL=https://www.google.com/search?q=%s&btnK
    restart: unless-stopped
    volumes:
      - app:/app
      - data:/data
volumes:
  app:
  data:
